version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  


  qatestdata:
    image: qatestdata:latest
    container_name: qatestdata-mongodb
    ports:
      - 8088:8088
    links:
      - mongodb